<?php

namespace Sandbox\BackBundle\Repository;

use Doctrine\ORM\Query\Expr;
use Symfony\Component\HttpFoundation\Request;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        $qb = $this->createQueryBuilder('c');

//        $query = $qb
//            ->where('c.type = :type')
//            ->setParameter('type', 'citadine')
//        ;

        $query = $qb;

        $result = $query->getQuery()->execute();

        return $result;
    }

    public function ajaxFindCar(Request $request)
    {
        $expr = new Expr();

        $result = $this->createQueryBuilder('c')
            ->select('c.type, c.id')
            ->where($expr->like('c.type', ':type'))
            ->setParameter('type', sprintf('%s%%', $request->query->get('q', '')))
            ->getQuery()
            ->getArrayResult();

        return $result;
    }

    public function ajaxGetCar($îds)
    {
        $expr = new Expr();

        $result = $this->createQueryBuilder('c')
            ->select('c.id, c.type')
            ->where($expr->in('c.id', ':ids'))
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getArrayResult();

        return $result;
    }
}
