<?php

namespace Sandbox\BackBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        $qb = $this->createQueryBuilder('c');

//        $query = $qb
//            ->where('c.type = :type')
//            ->setParameter('type', 'citadine')
//        ;

        $query = $qb;

        $result = $query->getQuery()->execute();

        return $result;
    }
}
