sandbox_rest:
    resource: "@SandboxRestBundle/Controller/"
    type:     rest

sandbox_back:
    resource: "@SandboxBackBundle/Controller/"
    type:     annotation
    prefix:   /back

sandbox_front:
    resource: "@SandboxFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
