sandbox_back:
    resource: "@SandboxBackBundle/Controller/"
    type:     annotation
    prefix:   /back

sandbox_front:
    resource: "@SandboxFrontBundle/Controller/"
    type:     annotation
    prefix:   /front


