parameters:
    car.form.type.class: Sandbox\FrontBundle\Form\Type\CarType
    car.handler.class: Sandbox\FrontBundle\Form\Handler\CarHandler
    car.manager.class: Sandbox\BackBundle\Services\CarManager
    symfony.form.class: Symfony\Component\Form\Form

services:
    car_form:
        factory_service: form.factory
        factory_method: createNamed
        class: %symfony.form.class%
        arguments:
            - car
            - car_form
            - null
            - { action: '/cars'}

    car_form_type:
        class: %car.form.type.class%
        tags:
            - { name: form.type, alias: car_form }

    car_handler:
        class: %car.handler.class%
        arguments: [@car_form, @request, @car_manager, @validator]
        scope: request